APP_NAME = "ASH-X"
WINDOW_TITLE = "ASH-X // SYSTEM INTERFACE"

CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

UI_FPS = 60

CORE_MIN_SIZE = 90
CORE_MAX_SIZE = 260

GESTURE_SMOOTHING = 0.25
